name: reVC linux premake x86

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-x86-librw_gl3_glfw-oal]
        buildtype: [debug, release]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Install System Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update

        sudo apt-get install -y \
          gcc-multilib g++-multilib \
          libopenal-dev:i386 \
          libsndfile1-dev:i386 \
          libmpg123-dev:i386 \
          libgl1-mesa-dev:i386 \
          libx11-dev:i386 \
          libxrandr-dev:i386 \
          libxinerama-dev:i386 \
          libxcursor-dev:i386 \
          libxi-dev:i386 \
          cmake

    - name: Compile GLFW and GLEW from source (i386)
      run: |
        git clone --depth 1 -b 3.4 https://github.com/glfw/glfw.git
        cd glfw
        cmake -B build \
          -DCMAKE_C_FLAGS="-m32" \
          -DCMAKE_CXX_FLAGS="-m32" \
          -DGLFW_BUILD_DOCS=OFF \
          -DGLFW_BUILD_TESTS=OFF \
          -DGLFW_BUILD_EXAMPLES=OFF
        cmake --build build -j$(nproc)
        sudo cmake --install build
        cd ..

        wget https://github.com/nigels-com/glew/releases/download/glew-2.3.1/glew-2.3.1.tgz
        tar -xzf glew-2.3.1.tgz
        cd glew-2.3.1
        make CFLAGS.EXTRA="-m32" LDFLAGS.EXTRA="-m32" LIBDIR=/usr/local/lib -j$(nproc)
        sudo make install LIBDIR=/usr/local/lib
        cd ..

    - name: Configure build
      run: |
        ./premake5 --with-librw gmake2

    - name: Build
      run: |
        cd build
        make config="${{matrix.buildtype}}_${{matrix.platform}}"

    - name: Move binaries to gamefiles
      run: |
        BUILD_TYPE="${{matrix.buildtype}}"
        DIR_NAME="${BUILD_TYPE^}"

        mv ./bin/${{matrix.platform}}/${DIR_NAME}/reVC ./gamefiles/

    - name: Upload artifact to actions
      uses: actions/upload-artifact@v4
      with:
        name: reVC_${{matrix.buildtype}}_${{matrix.platform}}
        path: ./gamefiles/*
